services:
  finapi:
    build: .
    container_name: finapi_app
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    restart: unless-stopped
